version: '3'


services:
  i2p_spider:
    restart: always
    image: spider_i2p:v3
    hostname: i2p_spider
    # 需要将i2p节点的port映射出来
    ports:
      - 23789:23789
      - 7657:7657
      - 4444:4444

    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
    # 将下列文件进行挂载
    # 1. 配置文件config
    # 2. 数据文件（流量、流日志）
    # 3. 日志文件
    # 4. 根目录
    volumes:
      - "/root/traffic_collection/spider_i2p/bushu/config:/app/config"
      - "/root/traffic_collection/spider_i2p/bushu/data:/app/data"
      - "/root/traffic_collection/spider_i2p/bushu/logs:/app/logs"
      - "/root:/root"
    # 设置特权模式
    privileged: true
