version: '3'


services:
  i2p_spider:
    restart: always
    image: spider_i2p:v2
    hostname: i2p_spider
    # 需要将i2p节点的port映射出来
    network_mode: "host"
    # ports:
    #   - 7070:7070
    #   - 21106:21106
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
    # 将下列文件进行挂载
    # 1. 配置文件config
    # 2. 数据文件（流量、流日志）
    # 3. 日志文件
    # 4. 根目录
    volumes:
      - "/home/aimafan/Documents/mycode/spider_i2p/config:/app/config"
      - "/home/aimafan/Documents/mycode/spider_i2p/data:/app/data"
      - "/home/aimafan/Documents/mycode/spider_i2p/logs:/app/logs"
      - "/root:/root"
    # 设置特权模式
    privileged: true
